name: Automaticke stahovani dat

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Stahni
      run: |-
        curl https://tgftp.nws.noaa.gov/data/observations/metar/stations/LKTB.TXT | jq . > letiste_brno.txt
