name: Automaticke stahovani dat

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Stahni
      run: |-
        wget -q https://tgftp.nws.noaa.gov/data/observations/metar/stations/LKTB.TXT
    - name: Uloz
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
