name: Automaticke stahovani dat

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Stahni data
      run: |-
        curl https://tgftp.nws.noaa.gov/data/observations/metar/stations/LKTB.TXT | jq . > letiste_brno.txt
    - name: Uloz, pokud nova data
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
